# Generated by Django 5.1.2 on 2024-10-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account_price',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
